### ISSUE TITLE
Support for memory limits

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [php-pdfbox/php-pdfbox#8]
Is it possible to add support for -Xms -Xmx parameters
```
java -Xms256m -Xmx2048m
```

**Comment by redcuillin** [comment]
I haven't tested, but I believe you should be able to include options like that when you instantiate the class.

`$pdfbox = new Pdfbox('/usr/bin/java -Xms256m -Xmx2048m', '/path/to/pdfbox-app.jar);`

**Comment by mariuszkrzaczkowski** [comment]
it doesn't work because it checks whether the file exists
https://github.com/php-pdfbox/php-pdfbox/blob/29878b278db07fdd8d16d14712cc061d02171c1d/src/Driver/Pdfbox.php#L39

```php
$file = new \Pdfbox\Processor\PdfFile(
	new \Pdfbox\Driver\Pdfbox(
		'/usr/bin/java  -Xms256m -Xmx2048m',
		ROOT_DIRECTORY . '/custom/pdfbox-app-2.0.30.jar',
		new \Psr\Log\NullLogger()
	)
);
```
```
Fatal error:  Uncaught Pdfbox/Exception/JavaNotFoundException: Java binary /usr/bin/java  -Xms256m -Xmx2048m not found. in /home/files/custom/vendor/php-pdfbox/php-pdfbox/src/Exception/JavaNotFoundException.php:23
Stack trace:
#0 /home/files/custom/vendor/php-pdfbox/php-pdfbox/src/Driver/Pdfbox.php(40): Pdfbox/Exception/JavaNotFoundException::create('/usr/bin/java  ...')
#1 /home/files/yf_scripts/pdfbox.php(57): Pdfbox/Driver/Pdfbox->__construct('/usr/bin/java  ...', '/home/files...', Object(Psr/Log/NullLogger))
#2 {main}
  thrown in /home/files/custom/vendor/php-pdfbox/php-pdfbox/src/Exception/JavaNotFoundException.php on line 23
```

I found places where it can be added to make it work properly
```php
private function run(array $commands): string
{
    array_unshift($commands, $this->pdfboxJar);
    array_unshift($commands, '-jar');
    array_unshift($commands, '-Xms128m');  // custom
    array_unshift($commands, '-Xmx1024m');  // custom
    array_unshift($commands, $this->java);

    $process = new Process($commands);
```
https://github.com/php-pdfbox/php-pdfbox/blob/29878b278db07fdd8d16d14712cc061d02171c1d/src/Driver/Pdfbox.php#L83-L87

**Comment by redcuillin** [comment]
You're right. Thanks for the suggestion, I will look into adding it as soon as possible. I have marked this task as an enhancement,

**Comment by redcuillin** [comment]
Adding this as an enhancement.
Ability to use any supported command line option seems sensible.
